# Generated by Django 4.2.3 on 2023-07-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='image',
            field=models.ImageField(default='https://cdn.britannica.com/69/155469-131-14083F59/airplane-flight.jpg', upload_to='plane_image'),
        ),
    ]
